# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:25
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - CLICKHOUSE_HTTP_PORT=8124
      - CLICKHOUSE_INTERSERVER_HTTP_PORT=9009
      - CLICKHOUSE_MYSQL_PORT=9004
      - CLICKHOUSE_POSTGRESQL_PORT=9005
      - CLICKHOUSE_SKIP_USER_SETUP=no
      - CLICKHOUSE_TCP_PORT=9000
    ports:
      - '8124:8124'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
volumes:
  clickhouse_data:
    driver: local
